#=====================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description:   Build OpenWrt with Image Builder
# Instructions:  https://openwrt.org/docs/guide-user/additional-software/imagebuilder
# Download from: https://downloads.openwrt.org/releases
#                https://downloads.immortalwrt.org/releases
#=====================================================================================

name: Build OpenWrt with ImageBuilder

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      releases_branch:
        description: "Select the releases branch"
        required: false
        default: "openwrt:22.03.3"
        type: choice
        options:
          - openwrt:22.03.3
          - openwrt:21.02.5
          - openwrt:19.07.10
          - openwrt:18.06.9
          - immortalwrt:21.02.5
          - immortalwrt:21.02.4
          - immortalwrt:21.02.3
      openwrt_board:
        description: "Select device board"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - s922x_s905x3_s905d_s912_s905l3a
          - s905d
          - s905d-ki-pro
          - s905x
          - s905x-tx9
          - s905x-t95
          - s905x-b860h
          - s905x-tbee
          - s905w
          - s905w-w95
          - s905w-x96w
          - s905w-x96-mini
          - s905l2
          - s905l2-wojia
          - s905l2-e900v21e
          - s905l3
          - s905l3-unt400g1
          - s905l3a
          - s905l3a-cm311
          - s905l3a-m401a
          - s905l3b
          - s905l3b-e900v22e
          - s905l3b-e900v22d
          - s905l3b-ip103h
          - s905lb-q96-mini
          - s905lb-r3300l
          - s912
          - s912-zyxq-fake
          - s912-h96pro-plus
          - s912-tx92
          - s912-z6-plus
          - s912-m8s-pro
          - s912-t95z-plus
          - s912-tx9-pro-3g
          - s912-tx9-pro-2g
          - s912-nexbox-a1
          - s912-nexbox-a2
          - s912-tx8-max
          - s912-x92
          - s912-phicomm-t1
          - s905x2
          - s905x2-x96max-2g
          - s905x2-km3
          - s922x
          - s922x-gtking
          - s922x-gtkingpro-h
          - s922x-reva
          - s922x-odroid-n2
          - s922x-ugoos-am6
          - s922x-ct2000
          - a311d
          - s905x3
          - s905x3-b
          - s905x3-hk1
          - s905x3-x96max
          - s905x3-h96max
          - s905x3-ugoosx3
          - s905x3-tx3
          - s905x3-tx3-bz
          - s905x3-a95xf3
          - s905x3-a95xf3-gb
          - s905x3-x96air
          - s905x3-x96air-gb
          - s905x3-ip1001m
          - s905x3-q1
          - s905x3-q2
          - s905x3-q1000
          - s905x3-a100
          - s905x3-2101
          - s905
          - s905-beelink-mini
          - s905-mxqpro-plus
          - rock5b
          - h88k
          - ipc-r
          - r66s
          - r68s
          - h66k
          - h68k
          - e25
          - nanopi-r5s
          - photonicat
          - eaidk-610
          - king3399
          - tn3399
          - kylin3399
          - hugsun-zm
          - crrc
          - beikeyun
          - l1pro
          - vplus
          - tanix-tx6
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "5.15.1_6.1.1"
        type: choice
        options:
          - 5.4.1_5.10.1_5.15.1
          - 5.4.1_5.10.1
          - 5.10.1_5.15.1
          - 5.15.1_6.1.1
          - 5.4.1
          - 5.10.1
          - 5.15.1
          - 6.1.1
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean
      kernel_repo:
        description: "Set the kernel repository"
        required: false
        default: "ophub/kernel"
        type: choice
        options:
          - ophub/kernel
      kernel_usage:
        description: "Set the tags of the stable kernel."
        required: false
        default: "stable"
        type: choice
        options:
          - stable
          - flippy
          - dev

env:
  TZ: America/New_York
  IMAGEBUILDER_SH: config-openwrt/imagebuilder/imagebuilder.sh

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Build Rootfs with Image Builder [ ${{ inputs.releases_branch }} ]
        id: imagebuilder
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          RELEASES_BRANCH="${{ inputs.releases_branch }}"
          chmod +x ${IMAGEBUILDER_SH}
          ${IMAGEBUILDER_SH} ${RELEASES_BRANCH}
          echo "RELEASES_TAG=${RELEASES_BRANCH/:/_}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Clean up server space
        if: ${{ steps.imagebuilder.outputs.status }} == 'success' && !cancelled()
        run: |
          cd openwrt/
          rm -rf $(ls . | grep -v "^bin$" | xargs) 2>/dev/null
          df -hT ${PWD}

      - name: Build OpenWrt firmware
        if: ${{ steps.imagebuilder.outputs.status }} == 'success' && !cancelled()
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: openwrt/bin/targets/*/*/*rootfs.tar.gz
          openwrt_board: ${{ inputs.openwrt_board }}
          openwrt_kernel: ${{ inputs.openwrt_kernel }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ${{ inputs.kernel_repo }}
          kernel_usage: ${{ inputs.kernel_usage }}
          gh_token: ${{ secrets.GH_TOKEN }}

      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: OpenWrt_imagebuilder_${{ env.RELEASES_TAG }}_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is OpenWrt firmware for Amlogic and Rockchip
            * Firmware information
            Default IP: 192.168.1.1
            Default username: root
            Default password: password
            Default WIFI name: OpenWrt
            Default WIFI password: none
            Install to EMMC: Login to OpenWrt → System → Amlogic Service → Install OpenWrt
