#========================================================================================================================
# https://github.com/ophub/amlogic-s9xxx-kernel-for-openwrt
# Description: Automatically Build OpenWrt for All S905x3-Boxs and Phicomm-N1
# Function: Workflows for Build All S905x3-Boxs and Phicomm-N1
# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
#========================================================================================================================

name: Test-amlogic-s9xxx-kernel-for-openwrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  UPLOAD_WETRANSFER: true
  RECENT_LASTEST: 10
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Build OpenWrt for S905x3-Boxs and Phicomm-N1
      id: build
      if: (!cancelled())
      run: |
        mkdir -p openwrt-armvirt
        curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_s905x3_.*/openwrt-armvirt-.*\.tar.gz" | head -n 1 > DOWNLOAD_URL
        [ -s DOWNLOAD_URL ] && wget -q -P openwrt-armvirt https://github.com/${GITHUB_REPOSITORY}/releases/download/$(cat DOWNLOAD_URL)
        sudo chmod +x make
        sudo ./make -d -b n1_x96_hk1_h96_octopus -k 5.4.77_5.9.8
        cd out/ && gzip *.img
        cp -f ../openwrt-armvirt/*.tar.gz . && sync
        echo "FILEPATH=$PWD" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
        echo "::set-output name=status::success"
        
    - name: SSH connection to Actions @ Ctrl+C to enter, Ctrl+D to exit
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Upload firmware directory for armvirt
      uses: actions/upload-artifact@v2
      if: steps.build.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        name: openwrt-armvirt-64-default-rootfs_${{ env.FILE_DATE }}
        path: ${{ env.FILEPATH }}/openwrt-armvirt-64-*
        retention-days: ${{ env.RECENT_LASTEST }}
        if-no-files-found: ignore

    - name: Upload firmware directory for Phicomm-N1
      uses: actions/upload-artifact@v2
      if: steps.build.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        name: openwrt_phicomm-n1_${{ env.FILE_DATE }}
        path: ${{ env.FILEPATH }}/openwrt_n1_*
        retention-days: ${{ env.RECENT_LASTEST }}
        if-no-files-found: ignore

    - name: Upload firmware directory for X96-Max+
      uses: actions/upload-artifact@v2
      if: steps.build.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        name: openwrt_x96-max_${{ env.FILE_DATE }}
        path: ${{ env.FILEPATH }}/openwrt_x96_*
        retention-days: ${{ env.RECENT_LASTEST }}
        if-no-files-found: ignore

    - name: Upload firmware directory for HK1-Box
      uses: actions/upload-artifact@v2
      if: steps.build.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        name: openwrt_hk1-box_${{ env.FILE_DATE }}
        path: ${{ env.FILEPATH }}/openwrt_hk1_*
        retention-days: ${{ env.RECENT_LASTEST }}
        if-no-files-found: ignore

    - name: Upload firmware directory for H96-Max-X3
      uses: actions/upload-artifact@v2
      if: steps.build.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        name: openwrt_h96-max-x3_${{ env.FILE_DATE }}
        path: ${{ env.FILEPATH }}/openwrt_h96_*
        retention-days: ${{ env.RECENT_LASTEST }}
        if-no-files-found: ignore

    - name: Upload firmware directory for Octopus-Planet
      uses: actions/upload-artifact@v2
      if: steps.build.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        name: openwrt_octopus-planet_${{ env.FILE_DATE }}
        path: ${{ env.FILEPATH }}/openwrt_octopus_*
        retention-days: ${{ env.RECENT_LASTEST }}
        if-no-files-found: ignore

    - name: Upload firmware to WeTransfer
      if: steps.build.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${{ env.FILEPATH }} 2>&1 | tee wetransfer.log
        echo "WET_URL=$(cat wetransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_ENV

    - name: Upload firmware to release
      uses: svenstaro/upload-release-action@v2
      if: steps.build.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.FILEPATH }}/*
        tag: openwrt_s905x3_phicomm-n1_${{ env.FILE_DATE }}
        overwrite: true
        file_glob: true
        body: |
          This is OpenWrt firmware for S905x3-Boxs and Phicomm-N1
          * Firmware information
          Default IP: 192.168.1.1
          Default username: root
          Default password: password
          Default WIFI name: OpenWrt
          Default WIFI password: none
          [WETRANSFER](${{ env.WET_URL }})
     
