#========================================================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Use Releases file to packaging
# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
#========================================================================================================================

name: Use Releases file to Packaging

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch [ official_master / lede ]"
        required: false
        default: "lede"
      openwrt_soc:
        description: "Choose Amlogic SoC."
        required: false
        default: "all"
      openwrt_kernel:
        description: "Choose kernel version."
        required: false
        default: "5.15.25_5.10.100"
      openwrt_size:
        description: "Set the rootfs size."
        required: false
        default: "960"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/compile-kernel/tools/script/ubuntu2204-make-openwrt-depends)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          # Input value validation
          ARR_BRANCH=("official" "lede")
          if [[ -n "${{ github.event.inputs.branch }}" && -n "$(echo "${ARR_BRANCH[@]}" | grep -w "${{ github.event.inputs.branch }}")" ]]; then
            RELEASES_BRANCH=${{ github.event.inputs.branch }}
          else
            RELEASES_BRANCH=lede
          fi
          echo "RELEASES_BRANCH=${RELEASES_BRANCH}" >> $GITHUB_ENV
          echo "COMPILE_STARTINGTIME=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV

      - name: Download OpenWrt Armvirt firmware
        id: down
        if: (!cancelled())
        run: |
          armvirt_tarfile_path="openwrt/bin/targets/armvirt/64"
          [ -d "${armvirt_tarfile_path}" ] || mkdir -p ${armvirt_tarfile_path}
          curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_s9xxx_${{ env.RELEASES_BRANCH }}.*/.*rootfs.tar.gz" | head -n 1 > DOWNLOAD_ARMVIRT
          [ -s DOWNLOAD_ARMVIRT ] && wget -q -P ${armvirt_tarfile_path} https://github.com/${GITHUB_REPOSITORY}/releases/download/$(cat DOWNLOAD_ARMVIRT)
          echo "::set-output name=status::success"

      - name: Build OpenWrt firmware
        if: steps.down.outputs.status == 'success' && !cancelled()
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: openwrt/bin/targets/*/*/*rootfs.tar.gz
          openwrt_soc: ${{ github.event.inputs.openwrt_soc }}
          openwrt_kernel: ${{ github.event.inputs.openwrt_kernel }}
          openwrt_size: ${{ github.event.inputs.openwrt_size }}

      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@main
        if: env.PACKAGED_STATUS == 'success' && !cancelled()
        with:
          tag: openwrt_s9xxx_${{ env.RELEASES_BRANCH }}_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is OpenWrt firmware for Amlogic s9xxx tv box
            * Firmware information
            Default IP: 192.168.1.1
            Default username: root
            Default password: password
            Default WIFI name: OpenWrt
            Default WIFI password: none
            Install to EMMC: Login to OpenWrt → System → Amlogic Service → Install OpenWrt
